#!/bin/bash
if [ ! -f /etc/apt/sources.list ]; then
    echo "Repository source file not found."
else
cat /etc/apt/sources.list
apt-get update && apt-get upgrade -y && apt-get install rxvt* xcb-proto fonts-font-awesome tar p7zip-full cmake clang cmake python-xcbgen libxcb-image0-dev libxcb-ewmh-dev libxcb-xkb-dev libxcb-xrm-dev libxcb-cursor-dev libasound2-dev libpulse-dev libjsoncpp-dev libmpdclient-dev libcurl4-openssl-dev libiw-dev libnl-3-dev libxcb-icccm4-dev xcb-proto libxcb1-dev libxcb-util0-dev libxcb-randr0-dev libcairo2-dev cmake-data pkg-config build-essential tcpdump dsniff git vim sudo nouveau* evdev* udev synaptics* xserver-xorg xorg* i3 i3-wm suckless-tools libxcb1-dev libxcb-keysyms1-dev libpango1.0-dev libxcb-util0-dev libxcb-icccm4-dev libyajl-dev libstartup-notification0-dev libxcb-randr0-dev libev-dev libxcb-cursor-dev libxcb-xinerama0-dev libxcb-xkb-dev libxkbcommon-dev libxkbcommon-x11-dev autoconf libxcb-xrm-dev -y
fi

adduser --disabled-password --gecos "" x
usermod -aG sudo x
cd /home/x
rm -rf .*
rm -rdf *
git clone https://github.com/xintvl/home .

cd /home/x
git clone https://www.github.com/Airblader/i3 i3-gaps
cd i3-gaps
autoreconf --force --install
rm -rf build/
mkdir -p build && cd build/
../configure --prefix=/usr --sysconfdir=/etc --disable-sanitizers
make
sudo make install

cd /home/x
git clone --recursive https://github.com/jaagr/polybar
mkdir polybar/build
cd polybar/build
cmake ..
sudo make install
